In [1]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler

data = [[100, 0.001],
        [8, 0.05],
        [50, 0.005],
        [88, 0.07],
        [4, 0.1]]

print("Data Asli")
print(data)

scaler = MinMaxScaler()

print("Data transfrom hasil normalisasi")

scaled = scaler.fit_transform(data)
print(scaled)


Data Asli
[[100, 0.001], [8, 0.05], [50, 0.005], [88, 0.07], [4, 0.1]]
Data transfrom hasil normalisasi
[[1.         0.        ]
 [0.04166667 0.49494949]
 [0.47916667 0.04040404]
 [0.875      0.6969697 ]
 [0.         1.        ]]


In [5]:
#Manual Normalization

def norm_manual(data):
    n_max = max(data)
    n_min = min(data)
    l_data = len(data) #panjang data
    
    for i in range(0, l_data):
        data[i] = (data[i]- n_min) / (n_max - n_min)
   
return data

SyntaxError: 'return' outside function (1928141653.py, line 11)

In [6]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler

data = [[100, 0.001],
        [8, 0.05],
        [50, 0.005],
        [88, 0.07],
        [4, 0.1]]

print("Data Asli")
print(data)

scaler = StandardScaler()

print("Data transfrom hasil normalisasi")

scaled = scaler.fit_transform(data)
print(scaled)

Data Asli
[[100, 0.001], [8, 0.05], [50, 0.005], [88, 0.07], [4, 0.1]]
Data transfrom hasil normalisasi
[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]


In [7]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()

oe = [
    ['State Polytechnics of Malang'],
    ['Electronic State Polytechnics of Surabaya'],
    ['State Polytechnics of Jakarta '],
    ['State Polytechnics of Padang'],
    ['State Polytechnics of Bandung']
    ]

print(ordinal_encoder.fit_transform(oe))

[[3.]
 [0.]
 [2.]
 [4.]
 [1.]]


In [8]:
from sklearn.feature_extraction import DictVectorizer
onehot_encoder = DictVectorizer()

oe = [
    {'name' : 'State Polytechnics of Malang'},
    {'name' :'Electronic State Polytechnics of Surabaya'},
    {'name' :'State Polytechnics of Jakarta '},
    {'name' :'State Polytechnics of Padang'},
    {'name' :'State Polytechnics of Bandung'}
    ]

print(onehot_encoder.fit_transform(oe).toarray())

[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]


In [9]:
from sklearn.preprocessing import OneHotEncoder
dummy_encoding = OneHotEncoder(drop = 'first')

de = [
    ['State Polytechnics of Malang'],
    ['Electronic State Polytechnics of Surabaya'],
    ['State Polytechnics of Jakarta ']
    ]

print(dummy_encoding.fit_transform(de).toarray())

[[0. 1.]
 [0. 0.]
 [1. 0.]]


In [10]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [11]:
from urllib import response
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


In [12]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = ['the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story']

X = vectorizer.fit_transform(corpus)

features = vectorizer.get_feature_names()

features

c:\Users\Nafarul Hamka\anaconda4\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['ate',
 'away',
 'cat',
 'end',
 'finally',
 'from',
 'had',
 'house',
 'little',
 'mouse',
 'of',
 'ran',
 'saw',
 'story',
 'the',
 'tiny']

In [15]:
z=open("orange.txt","r")
data = z.read().split()
data1 = z.read().splitlines()



from urllib import response
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')
response = vectorizer.fit_transform(data)
features = vectorizer.get_feature_names()
print(data1)
print("")
print(features)
print("")
print("result")

print(response)


[]

['000', '10', '12th', '14', '1869', '1870', '1878', '1883', '1oth', '2d', '313', '4th', '5024', '5517', '558', '7th', '82', '83', '84', '85', '87', '90', '9th', 'abjure', 'able', 'abound', 'absence', 'absolute', 'abuse', 'accident', 'accidental', 'accidents', 'accomplishment', 'account', 'accurately', 'accused', 'act', 'acted', 'addressed', 'ado', 'advantages', 'adventure', 'adventures', 'advice', 'advise', 'advised', 'affair', 'affairs', 'afraid', 'agitation', 'ago', 'ah', 'aid', 'air', 'alarm', 'albert', 'allowed', 'amateur', 'america', 'american', 'americans', 'amid', 'analysis', 'analytical', 'anatomy', 'anderson', 'angry', 'animal', 'answer', 'answered', 'anxiety', 'anxiously', 'apology', 'appeal', 'appears', 'archive', 'argue', 'arm', 'armed', 'arms', 'army', 'arrived', 'art', 'ary', 'ascended', 'ashes', 'ask', 'asked', 'assert', 'assume', 'astronomy', 'atlantic', 'attain', 'attention', 'attic', 'attics', 'attracted', 'augustine', 'authorities', 'aversion', 'await', 'away', '

c:\Users\Nafarul Hamka\anaconda4\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
